-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 08, 2018 at 11:54 AM
-- Server version: 10.1.16-MariaDB
-- PHP Version: 5.6.24

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `maturity`
--

-- --------------------------------------------------------

--
-- Table structure for table `pertanyaan`
--

CREATE TABLE `pertanyaan` (
  `id` int(11) NOT NULL,
  `dimensi` varchar(20) NOT NULL,
  `variabel` varchar(100) NOT NULL,
  `pertanyaan` varchar(500) NOT NULL,
  `bukti` varchar(200) DEFAULT NULL,
  `level_0` varchar(500) NOT NULL,
  `level_1` varchar(500) NOT NULL,
  `level_2` varchar(500) NOT NULL,
  `level_3` varchar(500) NOT NULL,
  `level_4` varchar(500) NOT NULL,
  `level_5` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `pertanyaan`
--

INSERT INTO `pertanyaan` (`id`, `dimensi`, `variabel`, `pertanyaan`, `bukti`, `level_0`, `level_1`, `level_2`, `level_3`, `level_4`, `level_5`) VALUES
(1, 'sumber daya', 'Supportive ICT Infrastructure/Service\r\nAvailability', 'Tersedia layanan TIK di instansi anda yang mendukung kegiatan anda.', 'Terdapat infrastruktur yang mendukung kegiatan TIK(semisal jaringan internet, WIFI, Komputer dsb)', 'Instansi Pusat/Pemerintah Daerah belum memiliki kebijakan internal untuk adanya mendukung infrastruktur IT.', 'Terdapat layanan TIK namun belum digunakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait layanan TIK.', 'Layanan TIK sudah ada, dan digunakan namun penggunaanya belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait layanan TIK.', 'Layanan TIK sudah ada, digunakan dan diawasi namun belum di evaluasi penggunaannya. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait layanan TIK.', 'Layanan TIK sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait layanan TIK.', 'Kebijakan internal terkait integrasi sistem aplikasi dievaluasi secara berkala. Hasil-hasil evaluasi diterapkan untuk memperbaiki kebijakan internal agar sesuai dengan kebutuhan Instansi Pusat/Pemerintah Daerah ataupun perubahan lingkungan dan teknologi'),
(2, 'sumber daya', 'strong leadership', 'Terdapat dukungan dari pemimpin dalam penggunaan TIK.', 'Upload data berupa kebijakan dan anggaran', 'Tidak terdapat dukungan dari pimpinan', 'Ada peran pemimpin tetapi belum didukung produk hukum dan hanya memiliki kewenangan di bidang TIK. Adapun data pendukungnya adalah Kebijakan atau aturan terkait layanan TIK.', 'kebijakan dari pimpinan sudah ada, dan di terapkan namun penerapannya belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait visi misi TIK.', 'Kebijakan pimpinan sudah ada, digunakan dan diawasi namun belum di evaluasi penggunaannya. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait visi misi TIK.', 'Kebijakan pemimpin sudah dilaksanakan secara menyeluruh, sudah diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait visi misi TIK.', 'Kebijakan pemimpin sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(3, 'sumber daya', 'Good Team Skills & Expertise', 'Team TIK terdiri dari orang yang berkompeten dan ahli di bidangnya', 'Data yng diberikan berupa data anggota team IT, sertifikat yang dimiliki dan evaluasi kinerja team IT', 'Tidak terdapat tim TIK.', 'Terdapat team IT namun belum memiliki program kerja. Adapun data pendukungnya adalah Kebijakan atau aturan terkait tim TIK.', 'Team It sudah ada, memiliki program kerja namun belum diketahui kompetensinya. Adapun data pendukungnya adalah Dokumentasi terkait tim TIK.', 'Team IT sudah ada, berjalan dan diawasi kompetensinya namun belum dievaluasi kompetensi dan keahliannya.Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait tim TIK.', 'Memiliki SDM TI yang kompeten  dan SOP pengelolaan TIK disempurnakan berdasarkan hasil evaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait tim TIK.', 'Team IT sudah ada, berjalan, diawasi dan dievaluasi, telah dikendalikan di Instansi Pusat/Pemerintah Daerah Saudara dan sudah di tingkatkan kemampuannya.'),
(4, 'sumber daya', 'good planning', 'Terdapat Blueprint atau Visi dan Arah kebijakan terkait pembangunan IT', 'dokumen terkait blueprint, laporan pengerjaan dan laporan pelaksanaan kebijakan yang telah dilaksanakan.', 'Tidak terdapat visi dan arah kebijakan', 'Visi dan arah kebijakan sedang di susun dan belum disahkan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perancanaan layanan TIK.', 'Visi dan arah kebijakan sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait visi misi TIK.', 'Visi dan arah kebijakan sudah ada, dijalankan dan diawasi namun belum dievaluasi di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait visi misi TIK.', 'Visi dan arah kebijakan sudah ada, dijalankan, diawasi dan dievaluasi, namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait visi misi TIK.', 'Pengukuran kepuasan masyarakat terhadap layanan sistem aplikasi sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(5, 'sumber daya', 'enough funding', 'Pendanaan untuk pembangunan infrastuktur TIK', 'Anggaran instansi', 'Tidak terdapat pendanaan', 'Terdapat kebijakan terkait pendanaan namun belum direalisasikan. Adapun data pendukungnya adalah Anggaran instansi anda.', 'Pendanaan sudah ada, tapi tidak sesuai rencana pembangunan jangka menengah nasional. Adapun data pendukungnya adalah Anggaran instansi anda.', 'Pendanaan sudah ada, dijalankan tapi belum terserap seluruhnya. Adapun data pendukungnya adalah Anggaran instansi anda.', 'Pendanaan sudah ada, dijalankan, dan dievaluasi serta mampu mendapat sumber pembiayaan lain untuk pembangunan layanan TIK. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait anggaran TIK.', 'Pendanaan sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(6, 'sumber daya', 'support interopability', 'Sistem dalam e-government dalam saling mendukung', NULL, 'Tidak terdapat dukungan terhadap interopabilitas', 'Sudah ada rencana terhadap interopabilitas lembaga namun belum dijalankan. Adapun data pendukungnya adalah Bukti sistem dalam e-government dapat saling berinteraksi langsung.', 'Interopabilitas lembaga sudah ada, dijalankan namun masih terbatas pada beberapa unit kerja. Adapun data pendukungnya adalah Bukti sistem dalam e-government dapat saling berinteraksi langsung.', 'Interopabilitas lembaga sudah ada, dijalankan pada seluruh unit kerja dalam instansi namun belum dievaluasi. Adapun data pendukungnya adalah Bukti sistem dalam e-government dapat saling berinteraksi langsung.', 'Interopabilitas lembaga sudah ada, dijalankan pada seluruh unit kerja dalam instansi dan sudah dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait anggaran TIK.', ''),
(7, 'sumber daya', 'training', 'Terdapat pelatihan terkait pemanfaatan e-government', 'daftar pelatihan yang diberikan kepada instansi terkait penggunaan e-government', 'Tidak terdapat pelatihan terkait e-Government.', 'Terdapat rencana pelatihan terkait e-Government namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait pelatihan di bidang TIK.', 'Pelatihan terkait e-Government sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Kebijakan atau aturan terkait pelatihan di bidang TIK.', 'Pelatihan terkait e-Government sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Kebijakan atau aturan terkait pelatihan di bidang TIK.', 'Pelatihan terkait e-Government sudah ada sudah ada, dijalankan, sesuai dengan rencana strategis dan sudah di evaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait visi misi TIK.', 'Pelatihan terkait e-Government sudah ada sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(8, 'sumber daya', 'good & clear organizational structure', 'Terdapat struktur organisasi dalam pengembangan TIK di instansi anda', 'Struktur organisasi dalam pembangunan e-government di daerah anda, bagaimana pelaksaanaan tugas, dan evaluasi serta peningkatan yang dilakukan', 'Tidak terdapat organisasi yang mengelola TIK.', 'Terdapat perencanaan namun belum dijalankan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perancanaan pengorganisasian tim TIK.', 'Struktur organisasi sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait organisasi TIK.', 'Struktur organisasi sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait organisasi TIK.', 'Struktur organisasi sudah ada, dijalankan, diawasi dan sudah dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait organisasi TIK.', 'Struktur organisasi sudah ada, dijalankan, diawasi, dievaluasi, dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(9, 'sumber daya', 'legal framework', 'Terdapat kerangka hukum terkait e-government di daerah anda', 'peraturan/kebijakan yang dikeluarkan instansi terkait e-government', 'Tidak terdapat peraturan terkait penggunaan e-Government.', 'Terdapat peraturan terkait penggunaan e-Government namun belum dijalankan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perancanaan kerangka hukum layanan e-Government.', 'Peraturan terkait penggunaan e-Government sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait kerangka hukum layanan e-Government.', 'Peraturan terkait penggunaan e-Government sudah ada, dijalankan dan diawasi namun belum dievaluasi di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait kerangka hukum layanan e-Government.', 'Peraturan terkait penggunaan e-Government sudah ada, dijalankan, diawasi dan dievaluasi, namun belum tingkatkan di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait kerangka hukum layanan e-Government.', 'Peraturan terkait penggunaan e-Government sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(10, 'sumber daya', 'awareness', 'Terdapat kesadaran akan pentingnya penggunaan e-government', NULL, 'Tidak terdapat kesadaran akan pentingnya penggunaan e-Government.', 'Terdapat rencana kebijakan terkait  penggunaan e-Government. Adapun data pendukungnya adalah Kebijakan atau aturan terkait penggunaan e-Government', 'Kebijakan penggunaan e-government sudah ada, dijalankan tapi layanan dapat berjalan tanpa e-Government. Adapun data pendukungnya adalah Dokumentasi terkait layanan e-Government.', 'Kebijakan penggunaan e-government sudah ada sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait layanan e-Government.', 'Kebijakan penggunaan e-government sudah ada sudah ada, dijalankan, diawasi dan dievaluasi, layanan tidak dapat berjalan tanpa e-government. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait layanan e-Government.', 'Kebijakan penggunaan e-government sudah ada, dijalankan, diawasi, dievaluasi, dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(11, 'sumber daya', 'system security', 'Terdapat sistem keamanan yang baik dalam pengaplikasian e-government', 'laporan mengenai sistem keamanan yang digunakan', 'Tidak ada sistem keamanan dalam pengaplikasian e-Government.', 'Terdapat sistem keamanan dalam pengaplikasian e-Government namun belum diterapkan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait penggunaan layanan keamanan di e-Government.', 'Sistem keamanan dalam pengaplikasian e-Government sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait layanan keamanan di e-Government', 'Pengukuran kepuasan masyarakat terhadap layanan sistem aplikasi e-Government sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait layanan keamanan di e-Government.', 'Sistem keamanan dalam pengaplikasian e-Government sudah ada, dijalankan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait layanan keamanan di e-Government', 'Sistem keamanan dalam pengaplikasian e-Government sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(12, 'sumber daya', 'creativity & innovation', 'Terdapat inovasi atau pengembangan dari institusi anda dalam penggunaan e-government.', 'laporan terkait inovasi dan pengembangan yang dilakukan.', 'Tidak terdapat inovasi dan pengembangan yang dilakukan dalam pengaplikasian e-Government.', 'Terdapat inovasi dan pengembangan yang dilakukan dalam pengaplikasian e-Government namun belum di lakukan.', 'Terdapat inovasi dan pengembangan yang dilakukan dalam pengaplikasian e-Government namun belum di lakukan. Adapun data pendukungnya adalah Dokumentasi terkait layanan keamanan di e-Government.', 'Inovasi dan pengembangan yang dilakukan dalam pengaplikasian e-Government sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait pengembangan e-Government.', 'Inovasi dan pengembangan yang dilakukan dalam pengaplikasian e-Government sudah ada, dijalankan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait pengembangan e-Government', 'Inovasi dan pengembangan yang dilakukan dalam pengaplikasian e-Government sudah ada, dijalankan, diawasi, dievaluasi, dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(13, 'sumber daya', 'user & stakeholder involvement', 'Keterlibatan pengguna dan pemangku kepentingan dalam pengembangan e-government', 'informasi yang berisi proses pengembangan e-government di instansi dan peran stakeholder yang terkait dalam pengembangannya.', 'Tidak ada keterlibatan apapun baik dari pengguna dan pemangku kepentingan dalam pengembangan e-Government.', 'Terdapat rencana memperlibatkan pengguna dan pemangku kepentingan dalam pengembangan e-Government namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait pengguna e-Government.', 'Keterlibatan baik dari pengguna dan pemangku kepentingan dalam pengembangan e-Government sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait pengguna e-Government.', 'Keterlibatan baik dari pengguna dan pemangku kepentingan dalam pengembangan e-Government sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait pengguna e-Government.', 'Keterlibatan baik dari pengguna dan pemangku kepentingan dalam pengembangan e-Government sudah ada, dijalankan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait pengguna e-Government.', 'Keterlibatan baik dari pengguna dan pemangku kepentingan dalam pengembangan e-Government sudah ada, dijalankan, diawasi, dievaluasi, dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(14, 'sumber daya', 'citizen computer literacy', 'Terdapat pelayanan e-government yang digunakan oleh masyarakat sekitar', 'data penggunaan aplikasi e-government di instansi anda oleh penduduk daerah, jika data belum ada tunjukan screenshoot aplikasinya.', 'Tidak terdapat layanan sistem aplikasi e-Government.', 'Terdapat perencanaan layanan sistem aplikasi e-Government namun belum dijalankan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait penggunaan e-Government.', 'Layanan sistem aplikasi e-Government sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait layanan e-Government terhadap masyarakat.', 'Layanan sistem aplikasi e-Government sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait penggunaan e-Government.', 'Layanan sistem aplikasi e-Government sudah ada, dijalankan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait penggunaan e-Government di masyarakat.', 'Layanan sistem aplikasi e-Government sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(15, 'pengungkit', 'supportive government policy', 'Kebijakan pemerintahan yang mendukung e-govenment', '', 'Tidak terdapat kebijakan internal terkait dukungan kebijakan pemerintah', 'Terdapat kebijakan pendukung penerapan TIK namun belum dijalankan. Adapun data pendukungnya adalah Kebijakan atau aturan yang mendukung e-government ', 'Terdapat kebijakan pendukung penerapan TIK yang dijalankan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi kebijakan terkait.', 'Terdapat kebijakan pendukung penerapan TIK, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait kegiatan TIK.', 'Terdapat kebijakan pendukung penerapan TIK yang sudah dijalankan diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait kebijakan pendukung e-government.', 'Kebijakan internal terkait dukungan kebijakan pemerintah sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(16, 'pengungkit', 'good partnership with other institution', 'Kebijakan mengenai kerjasama dengan instansi lain ', NULL, 'Tidak ada kebijakan pendukung', 'Terdapat kebijakan kerjasama  namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perencanaan kerjasama instansi.', 'Kebijakan kerjasama sudah dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi kebijakan terkait.', 'Kebijakan kerjasama sudah dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait kerjasama instansi.', 'Kebijakan kerjasama sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait kerjasama instansi.', 'Kebijakan eksternal terkait kemitraan yang baik dengan Institusi lain sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(17, 'pengungkit', 'political support & stability', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki kebijakan eksternal terkait dukungan politik dan stabilitas', NULL, 'Tidak ada kebijakan pendukung', 'Terdapat kebijakan ekternal terkait dukungan politik dan stabilitas. Adapun data pendukungnya adalah Kebijakan atau aturan terkait dukungan dan stabilitas politik.', 'Kebijakan eksternal terkait dukungan politik dan stabilitas sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi kebijakan terkait.', 'Kebijakan eksternal terkait dukungan politik dan stabilitas yang baik sudah ada, dijalankan dan diawasi namun belum dievaluasi di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait partai politik.', 'Kebijakan eksternal terkait dukungan politik dan stabilitas sudah ada, dijalankan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait kebijakan untuk partai politik.', 'Kebijakan eksternal terkait dukungan politik dan stabilitas sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(18, 'pengungkit', 'good project management', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki Tata Kelola proyek IT pada instansi', NULL, 'Tidak terdapat kebijakan internal terkait pengelolaan proyek TIK.', 'Terdapat kebijakan manajemen proyek namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perencanaan proyek  (Business Process Reengineering).', 'Kebijakan manajemen proyek sudah dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi Business Case Document (BCD) atau Business Requirement Document (BRD).', 'Kebijakan manajemen proyek sudah dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait proyek IT.', 'Kebijakan manajemen proyek sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporanproject charter)  terkait proyek IT.', 'Kebijakan internal terkait pengelolaan proyek TIK sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(19, 'nilai', 'better business process', 'Kondisi proses bisnis di instansi saudara.', 'Dibuktikan dengan gambaran bisnis proses\r\n', 'Tidak ada perencanaan terkait BPR (Business Process Reengineering).', 'BPR (Business Process Reengineering) sudah direncanakan tetapi belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perencanaan BPR (Business Process Reengineering).', 'BPR (Business Process Reengineering) sudah direncanakan, dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi BPR.', 'BPR (Business Process Reengineering)  sudah direncanakan, dilaksanakan, diawasi tetapi belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait bisnis proses.', 'BPR (Business Process Reengineering)  sudah direncanakan, dilaksanakan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait business process reengineering.', 'Alur kerja terkait e-Government sudah ada, dijalankan, diawasi, dievaluasi, dan sudah ditingkatkan oleh Instansi Pusat/Pemerintah Daerah Saudara.'),
(20, 'nilai', 'supportive cultural environment', 'Kondisi budaya organisasi di instansi saudara.', 'kebiasaan dalam kelompok IT ataupun pengguna serta pegawai di instansi anda yang menggerakkan adanya penggunaan e-government.', 'Belum ada aturan dalam mendorong budaya organisasi yang suportif.', 'Aturan dalam mendorong budaya organisasi yang suportif sudah ada, namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait budaya organisasi yang suportif.', 'Aturan dalam mendorong budaya organisasi yang suportif sudah ada, dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi (foto atau laporan) terkait kegiatan yang mencerminkan budaya organisasi.', 'Aturan dalam mendorong budaya organisasi yang suportif sudah ada, dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait budaya kerja di organisasi.', 'Aturan dalam mendorong budaya organisasi yang suportif sudah ada, dilaksanakan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait budaya kerja di organisasi.\n', 'Budaya kerja yang mendukung penerapan e-government sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan oleh Instansi Pusat/Pemerintah Daerah Saudara.'),
(21, 'nilai', 'electronic transaction', 'Mekanisme transaksi elektronik di instansi anda.', 'data terkait e-procurement, e-banking, dsb', 'Belum ada mekanisme transaksi elektronik.', 'Sudah ada mekanisme transaksi elektronik namun belum dilaksanakan secara menyeluruh. Adapun data pendukungnya adalah Kebijakan atau aturan terkait mekanisme transaksi elektronik.', 'Sudah ada mekanisme transaksi elektronik, sudah dilaksanakan secara menyeluruh namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait transaksi elektronik.', 'Sudah ada mekanisme transaksi elektronik, sudah dilaksanakan secara menyeluruh, sudah diawasi, namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait transaksi elektronik.', 'Sudah ada mekanisme transaksi elektronik, sudah dilaksanakan secara menyeluruh, sudah diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait mekanisme transaksi elektronik.', 'Penggunaan transaksi elektronik sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(22, 'nilai', 'trust', 'Kepercayaan masyarakat dalam menggunakan layanan e-government di instansi anda.', 'pengujian data atau informasi terhadap aplikasi di instansi anda.', 'Masyarakat masih menggunakan jalur tradisional (offline)', 'Masyarakat sudah mengakses sistem  e-Government  tetapi sebatas layanan informasional saja. Adapun data pendukungnya adalah Kebijakan atau aturan terkait sosialisasi penggunaan layanan di instansi anda.', 'Masyarakat menggunakan layanan transaksional  e-Government yang telah disediakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait penggunaan layanan oleh masyarakat (jumlah pengguna, atau akun yang terdaftar).', 'Masyarakat menggunakan layanan transaksional  e-Government yang telah disediakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait penggunaan layanan oleh masyarakat.', 'Masyarakat menggunakan layanan transaksional  e-Government yang telah disediakan, diawasi dan sudah dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait penggunaan layanan oleh masyarakat.', 'Pengukuran kepuasan masyarakat terhadap layanan sistem aplikasi sudah ada, dijalankan, diawasi, dievaluasi, dan sudah  ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(23, 'nilai', 'e-participation', 'Partisipasi publik melalui TIK di instansi anda.', 'Dibuktikan dengan penetrasi kunjungan aplikasi e-government anda', 'Belum ada partisipasi publik melalui TIK', 'Pemerintah sudah membangun sistem untuk memfasilitasi publik berpartisipasi melalui TIK, namun belum mendapat respon dari publik. Adapun data pendukungnya adalah Kebijakan atau aturan terkait partisipasi publik pada layanan di instansi anda.', 'Pemerintah sudah membangun sistem untuk memfasilitasi publik berpartisipasi melalui TIK, sudah mendapat respon yang baik, namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi (screenshot) terkait sistem partisipasi masyarakat seperti lapor.go.id (layanan aspirasi dan pengaduan online rakyat) pada instansi anda.', 'Pemerintah sudah membangun sistem untuk memfasilitasi publik berpartisipasi melalui TIK, sudah mendapat respon yang baik, diawasi, namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait penggunaan layanan e-participation  oleh masyarakat.', 'Pemerintah sudah membangun sistem untuk memfasilitasi publik berpartisipasi melalui TIK, sudah mendapat respon yang baik, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait penggunaan layanan e-participation.', 'Pengukuran penggunaan oleh masyarakat terhadap layanan sistem aplikasi sudah ada, dijalankan, diawasi, dievaluasi, dan sudah ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(24, 'nilai', 'using portal/application', 'Penggunaan portal/ aplikasi di intansi anda.', 'Dibuktikan dengan list dan link terhadap aplikasi berupa, web, aplikasi hp, dsb', 'Portal web digunakan sebatas untuk diseminasi informasi yang bersifat statis.', 'Portal web digunakan untuk diseminasi informasi dan pemasukan data yang bersifat interaktif, namun belum digunakan untuk layanan terpadu dan terintegrasi. Adapun data pendukungnya adalah Kebijakan atau aturan terkait penggunaan web portal/aplikasi.', 'Portal web digunakan untuk diseminasi informasi, layanan terpadu dan terintegrasi, namun belum diawasi oleh pihak terkait. Adapun data pendukungnya adalah Dokumentasi (screenshot) terkait penggunaan web portal/aplikasi.', 'Portal web digunakan untuk diseminasi informasi, layanan terpadu dan terintegrasi, diawasi, namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan (contoh dari divisi TI) terkait penggunaan web portal.', 'Portal web digunakan untuk diseminasi informasi, layanan terpadu dan terintegrasi, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan) terkait penggunaan web portal atau aplikasi.', 'Pengukuran kepuasan masyarakat terhadap layanan sistem aplikasi sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(25, 'dampak', 'User Satisfaction', 'Standar pelayanan publik di instansi saudara.', NULL, 'Tidak terdapat standar pelayanan publik.', 'Terdapat standar pelayanan publik namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait standar pelayanan publik.\n', 'Terdapat standar pelayanan publik, sudah dilaksanakan, namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait standar pelayanan publik.', 'Terdapat standar pelayanan publik, sudah dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait standar pelayanan.', 'Terdapat standar pelayanan publik, sudah dilaksanakan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait standar pelayanan publik.', 'Pengukuran kepuasan masyarakat terhadap layanan sistem aplikasi sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(26, 'dampak', 'Self-Sustanaible Revenue', 'Kontribusi pendapatan secara berkelanjutan dari penggunaan layanan e-government di instansi saudara.', NULL, 'Tidak ada pendapatan berkelanjutan dari penggunaan layanan e-government.', 'Terdapat pendapatan berkelanjutan dari penggunaan layanan e-government. Adapun data pendukungnya adalah Kebijakan atau aturan terkait pendapatan berkelanjutan dari layanan e-government.', 'Pendapatan yang berkelanjutan dari penggunaan layanan e-government sudah ada, dijalankan tapi belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait pendapatan berkelanjutan dari layanan e-government.', 'Pendapatan yang berkelanjutan dari penggunaan layanan e-government sudah ada, dijalankan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait pendapatan berkelanjutan dari layanan e-government.', 'Pendapatan yang berkelanjutan dari penggunaan layanan e-government sudah ada, dijalankan, diawasi, dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait pendapatan berkelanjutan dari layanan e-government.', 'Pendapatan berkelanjutan Instansi Pusat/Pemerintah Daerah Saudara dari penggunaan layanan e-Government sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan.'),
(27, 'dampak', 'Open Government', 'Kondisi keterbukaan data dalam instansi saudara.', NULL, 'Tidak terdapat kebijakan open government.', 'Terdapat konsep Kebijakan terkait hak warganegara \n untuk mengakses dokumen dan proses pemerintah dengan Layanan e-Government namun belum dijalankan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait open government.', 'Terdapat konsep Kebijakan terkait hak warganegara untuk mengakses dokumen dan proses pemerintah dengan Layanan e-Government. Adapun data pendukungnya adalah sudah ada, dilaksanakan tetapi belum diawasi.', 'Kebijakan terkait hak warganegara untuk mengakses dokumen dan proses pemerintah dengan Layanan e-Government  sudah ada, dilaksanakan dan diawasi namun belum dievaluasi. adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait open government.', 'Kebijakan terkait hak warganegara untuk mengakses dokumen dan proses pemerintah dengan Layanan e-Government sudah ada, dijalankan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait open government', 'Kebijakan terkait hak warganegara untuk mengakses dokumen dan proses pemerintah dengan Layanan e-Government di Instansi Pusat/Pemerintah Daerah Saudara sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan.'),
(28, 'dampak', 'Good Governance', 'Kondisi tata kelola TIK di instansi saudara.', NULL, 'Tidak terdapat tata kelola TIK.', 'Terdapat kebijakan atau aturan terkait tata kelola TIK tetapi belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait tata kelola TIK.', 'Tata kelola TIK sudah ada, dijalankan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi terkait penerapan tata kelola TIK.', 'Tata kelola TIK sudah ada, dijalankan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait tata kelola TIK.', 'Tata kelola TIK sudah ada, dijalankan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait tata kelola TIK.', 'Kebijakan internal terkait rencana induk SPBE dievaluasi secara berkala. Hasil-hasil evaluasi diterapkan untuk memperbaiki kebijakan agar sesuai dengan kebutuhan Instansi Pusat/Pemerintah Daerah ataupun perubahan lingkungan dan teknologi.'),
(29, 'dampak', 'Prototype', 'Kondisi prototipe sistem e-government di instansi saudara.', NULL, 'Tidak terdapat prototipe sistem e-Government di Instansi Pusat/Pemerintah Daerah Saudara.', 'Terdapat prototipe sistem e-Government di Instansi Pusat/Pemerintah Daerah Saudara namun belum dijalankan. adapun data pendukungnya adalah Kebijakan atau aturan terkait prototipe sistem e-government.', 'Prototipe sistem e-Government di Instansi Pusat/Pemerintah Daerah Saudara sudah ada dan dijalankan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi prototipe sistem e-government.', 'Prototipe sistem e-government sudah ada, dijalankan dan diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait prototipe sistem.', 'Prototipe sistem e-government sudah ada, dijalankan, diawasi dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait prototipe sistem e-government.', 'Prototipe sistem e-Government di Instansi Pusat/Pemerintah Daerah Saudara sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan.'),
(30, 'pengungkit', 'Good Change Management', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki kebijakan internal terkait manajemen perubahan', NULL, 'Tidak terdapat kebijakan internal terkait manajemen perubahan di Instansi Pusat/Pemerintah Daerah Saudara.', 'Terdapat kebijakan manajemen proyek namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perencanaan BPR (Business Process Reengineering).', 'Kebijakan manajemen proyek sudah dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi perubahan seperti request of change (RFC)', 'Kebijakan manajemen proyek sudah dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait bisnis proses.', 'Kebijakan manajemen proyek sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait business change management.', 'Kebijakan internal terkait manajemen perubahan sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(31, 'pengungkit', 'Monitoring & Evaluation', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki kebijakan internal terkait pemnatauan dan evaluasi program TIK', NULL, 'Tidak terdapat kebijakan internal terkait pemantauan dan evaluasi program TIK.', 'Terdapat konsep kebijakan internal terkait pemantauan dan evaluasi program TIK. Adapun data pendukungnya adalah Kebijakan atau aturan pengawasan dan evaluasi.', 'Kebijakan internal terkait dukungan kebijakan pemerintah sudah ada, dijalankan dan diawasi namun belum dievaluasi di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Dokumentasi BPR.', 'Kebijakan internal terkait pemantauan dan evaluasi program TIK.sudah ada, dijalankan, diawasi dan dievaluasi, namun belum dikendalikan di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) atau SOP pada bagian pengawasan dan evaluasi IT.', 'Kebijakan internal terkait pemantauan dan evaluasi program TIK sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait pengawasan dan evaluasi IT.', 'Kebijakan internal terkait pemantauan dan evaluasi program TIK.sudah ada, dijalankan dan diawasi namun belum dievaluasi di Instansi Pusat/Pemerintah Daerah Saudara.'),
(32, 'pengungkit', 'Top Management Support', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki kebijakan internal terkait dukungan manajemen puncak', NULL, 'Tidak terdapat kebijakan internal terkait dukungan manajemen puncak.', 'Terdapat dukungan pimpinan namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait perencanaan BPR (Business Process Reengineering).', 'Kebijakan dukungan pimpinan sudah dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi kebijakan terkait. seperti surat keputusan.', 'Kebijakan dukungan pimpinan sudah dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait kebijakan pimpinan.', 'Kebijakan dukungan pimpinan sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan).', 'Kebijakan internal terkait dukungan manajemen puncak sudah ada, dijalankan dan diawasi namun belum dievaluasi di Instansi Pusat/Pemerintah Daerah Saudara.'),
(33, 'pengungkit', 'Good Outsourcing Strategy', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki kebijakan eksternal terkait strategi outsourcing yang baik', NULL, 'Tidak terdapat kebijakan eksternal terkait strategi outsourcing yang baik.', 'Terdapat kebijakan outsourcing IT namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait outsourcing IT.', 'Kebijakan outsourcing IT sudah dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi kebijakan terkait outsourcing IT.', 'Kebijakan outsourcing IT sudah dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait outsourcing IT.', 'Kebijakan outsourcing IT sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait outsourcing IT.', 'Kebijakan eksternal terkait strategi outsourcing yang baik dengan Institusi lain sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(34, 'pengungkit', 'Good Coordination', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki kebijakan internal terkait koordinasi tim TIK', NULL, 'Tidak terdapat kebijakan internal terkait koordinasi tim TIK di Instansi Pusat/Pemerintah Daerah Saudara.', 'Terdapat kebijakan koordinasi namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait koordinasi antara unit kerja.', 'Kebijakan koordinasi dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi kebijakan terkait.', 'Kebijakan koordinasi dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait koordinasi unit kerja.', 'Kebijakan koordinasi sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait koordinasi unit kerja.', 'Kebijakan internal koordinasi tim TIK sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.'),
(35, 'pengungkit', 'Reward & Recognition', 'Instansi Pusat/Pemerintah Daerah Saudara memiliki kebijakan internal terkait penghargaan dan pengakuan kompetensi TIK', NULL, 'Tidak terdapat kebijakan internal terkait penghargaan dan pengakuan kompetensi TIK', 'Terdapat pemberian pengakuan dan penghargaan namun belum dilaksanakan. Adapun data pendukungnya adalah Kebijakan atau aturan terkait pemberian penghargaan.', 'Kebijakan pemberian pengakuan dan penghargaan sudah dilaksanakan namun belum diawasi. Adapun data pendukungnya adalah Dokumentasi kebijakan terkait.', 'Kebijakan pemberian pengakuan dan penghargaan sudah dilaksanakan, diawasi namun belum dievaluasi. Adapun data pendukungnya adalah Tupoksi (tugas pokok dan fungsi) bagian pengawasan terkait pemberian pengakuan dan penghargaan.', 'Kebijakan pemberian pengakuan dan penghargaan sudah dilaksanakan, diawasi, dan dievaluasi. Adapun data pendukungnya adalah Hasil evaluasi (notulensi rapat/laporan)  terkait terkait pemberian pengakuan dan penghargaan.', 'Kebijakan internal penghargaan dan pengakuan kompetensi TIK sudah ada, dijalankan, diawasi, dievaluasi, dikendalikan namun belum ditingkatkan di Instansi Pusat/Pemerintah Daerah Saudara.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pertanyaan`
--
ALTER TABLE `pertanyaan`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pertanyaan`
--
ALTER TABLE `pertanyaan`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
